site_name: OllamaPy - AI Skills & Chat Interface
site_url: https://scienceisverycoool.github.io/OllamaPy
repo_url: https://github.com/ScienceIsVeryCool/OllamaPy
repo_name: ScienceIsVeryCool/OllamaPy
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quick-start.md
  - Features:
    - Chat Interface: features/chat.md
    - Skills System: features/skills.md
    - Vibe Tests: features/vibe-tests.md
  - Skill Editor:
    - Overview: skill-editor/index.md
    - Getting Started: skill-editor/getting-started.md
    - Creating Skills: skill-editor/creating-skills.md
    - API Reference: skill-editor/api.md
  - Skills Library: 
    - Overview: skills/index.md
    - Built-in Skills: skills/built-in.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md
    - Release Process: development/releases.md
  - API Reference: api/

plugins:
  - search
  - include-markdown

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ScienceIsVeryCool/OllamaPy
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/ollamapy/
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/scienceisverycoool/ollamapy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html